### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by knkms** [netsandbox/docker-rt#13]
Hi!

No really an issue but more of a request:

Could you add more environment variables such as WebDomain, rtname, Organization etc.? I don't know how to do this myself :(.

For setting it up:
![afbeelding](https://user-images.githubusercontent.com/66147407/229641973-fb36664d-8294-447e-910c-be9c312e6af9.png)

Best regards,

knkms

**Comment by netsandbox** [comment]
This Docker image is intended for development use only, and I think the mentioned configurations are not necessary in a development environment.
