### ISSUE TITLE
RT 5.0.4: Installation error

### ISSUE THREAD

**Issue by yawaraziz** [netsandbox/docker-rt#17]
Hi @netsandbox ,

I hope you will be fine.

So I created a docker-compose.yml file to run RT using your image which obviously supports SQLite by default but I needed to run MySQL DB at the back-end. This image lacks Perl drivers for MySQL resulting an error of missing dependency called `libdbd-mysql-perl` & some other troubleshooting & debug tools incl. `iputils` & `net-tools` which are necessary to checkup the inter-container connectivity & DB connectivity as well with MySQL.

Therefore, I downloaded your Dockerfile & altered it to install the above tools using Debian 12 as base image which looked as under:

>FROM debian:12 AS package-installer
LABEL org.opencontainers.image.authors="Christian Loos <cloos@netsandbox.de>"
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update && \
    apt-get install -y \
    libdbd-mysql-perl \
    iputils-ping \
    net-tools \
    traceroute && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
FROM netsandbox/request-tracker-base:latest
COPY --from=package-installer / /
WORKDIR /usr/local/src
RUN curl -fsSL "https://download.bestpractical.com/pub/rt/release/rt-5.0.4.tar.gz" -o rt.tar.gz \
    && echo "916d870d22d92027f843798be6f880aaf1517aebc3f6ab25f456f4e772f4834d  rt.tar.gz" | sha256sum -c \
    && tar -xzf rt.tar.gz \
    && cd rt-5.0.4 \
    && ./configure \
    --enable-developer \
    --enable-externalauth \
    --enable-gd \
    --enable-gpg \
    --enable-graphviz \
    --enable-smime \
    --with-db-type=mysql \
    --with-web-handler=standalone \
    && make install \
    && mkdir --mode=0600 --parents /opt/rt5/var/data/{gpg,smime} \
    && make initialize-database \
    && cd .. && rm -rf /usr/local/src/*
WORKDIR /opt/rt5
COPY RT_SiteConfig.pm etc/
VOLUME /opt/rt5
COPY docker-entrypoint.sh /usr/local/bin/
ENTRYPOINT ["docker-entrypoint.sh"]
EXPOSE 80
CMD ["/opt/rt5/sbin/rt-server"]

Here come 2 problems:

1. While building the docker image using Dockerfile, it tries to `make initialize-database` which doesn't go successful as during image building, it tries to connect with DB. Since, the DB isn't found, the image building goes unsuccessful & I need to comment out this step in order to make image building successful. This result giving me errors in `docker logs -f <rt_container_name>` when container becomes up saying `xxxx.tbl` table not found. Therefore, my question is how we can manually upload DB schema & table info in our database to connect with RT frond-end. Having DB schema & table data is mandatory because I believe after first successful login, the RT tries to execute first setup wizard which in my case, unable to see.

2. I can see that the installation of RT itself is successful. I can see the `login page` in Web UI & can see that login is successful in the docker logs but then I receive an error message in Web UI saying `Page not found`. This involves page redirection. Can you help me how I can make it successful? Below is how my `RT_SiteConfig.pm` looks like
[RT_SiteConfig.txt](https://github.com/netsandbox/docker-rt/files/12568547/RT_SiteConfig.txt)

Any help in regards of above two will be appreciated.

Thanks @netsandbox

**Comment by netsandbox** [comment]
@yawaraziz can you share your `docker-compose.yml` file.

**Comment by yawaraziz** [comment]
Yes please.

[docker-compose.yml.txt](https://github.com/netsandbox/docker-rt/files/12599986/docker-compose.yml.txt)

Below are contents of `RT_SiteConfig.pm`

Set( $CommentAddress, 'root@192.168.122.204' );
Set( $CorrespondAddress, 'root@192.168.122.204' );
Set( $DatabaseHost, 'mariadb-rt' );
Set( $DatabaseName, 'rt5' );
Set( $DatabasePassword, 'Testing12345' );
Set( $DatabasePort, '3306' );
Set( $DatabaseType, 'mysql' );
Set( $DatabaseUser, 'rt_user' );
Set( $Organization, 'test.com' );
Set( $OwnerEmail, 'root@192.168.122.204' );
Set( $WebDomain, '192.168.122.204' );
Set( $WebPort, '80' );
Set( $rtname, 'test.com' );
Set( $WebDomain, 'rt.test.com' );

@netsandbox In ideal situation, the command in your `Dockerfile` which is `make initialize-database` should not be there as after successful installation, once RT setup is completed successfully, RT itself executes setup wizard when the Web GUI page is first appear.

**Comment by yawaraziz** [comment]
@netsandbox With variations in new version of RT w.e.f 5.0 to 5.0.4, your Dockerfile & image have missed things a lot. It has not perl-libdbd-* drivers installed by default. Since this image is also missing net-tools & iputils, you cannot even download from the internet from inside the container & then commit to a new image.

**Comment by netsandbox** [comment]
@yawaraziz how will `net-tools` and `iputils-ping` help you download anything from the internet?

`libdbd-sqlite3-perl` is included because this Docker image is only intended for development or testing, not for production use, and here is SQLite sufficient.

By the way, `COPY --from=package-installer / /` is one of the worst thinks I ever saw in a Dockerfile.
Why don't you just copy my Dockerfile and install all the packages that you need with `apt-get`, before the RT in configured?

**Comment by yawaraziz** [comment]
Aaahh.. So it for development only.. Ok @netsandbox Thank you Sir for valuable time & feedback

**Comment by yawar-bhatti** [comment]
With this for development, you can close this issue @netsandbox 

Many thanks Sir
