### ISSUE TITLE
Use mysql instance in host

### ISSUE THREAD

**Issue by suoko** [netsandbox/docker-rt#8]
Hi,

I was trying to use your docker to connect to an existing mysql database running on the host machine.
 ```
    --with-db-type=mysql \
    --with-db-host=host.docker.internal  \
    --with-db-port=3306 \
    --with-db-rt-host=host.docker.internal  \
    --with-db-dba=debian-sys-maint \
    --with-db-database=rtdb \
    --with-db-rt-user=rtuser \
    --with-db-rt-pass=rtuser \
```

and then run the docker with     option `--add-host host.docker.internal:host-gateway \`

Is that the right way ?
Should I clone your docker recipe from docker hub ?

**Comment by netsandbox** [comment]
These docker images are only for testing and not for production.
So they don't support connecting to an external database.
